"""empty message

Revision ID: 7663bc72a775
Revises: 53748fc24fa3
Create Date: 2022-09-13 16:22:04.453327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7663bc72a775'
down_revision = '53748fc24fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contribution', sa.Column('charity_id2', sa.String(), nullable=True))
    op.drop_constraint('contribution_charity_id_fkey', 'contribution', type_='foreignkey')
    op.drop_column('contribution', 'charity_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contribution', sa.Column('charity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('contribution_charity_id_fkey', 'contribution', 'charity', ['charity_id'], ['id'])
    op.drop_column('contribution', 'charity_id2')
    # ### end Alembic commands ###
