"""empty message

Revision ID: 795859db561d
Revises: 9c13a1872a03
Create Date: 2022-09-13 16:33:07.344547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795859db561d'
down_revision = '9c13a1872a03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('charity_id2', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contribution')
    # ### end Alembic commands ###
