"""empty message

Revision ID: efdcbe683312
Revises: 3dac20987e76
Create Date: 2022-09-12 22:00:48.284255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdcbe683312'
down_revision = '3dac20987e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contribution', sa.Column('charity_id', sa.Integer(), nullable=False))
    op.alter_column('contribution', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'contribution', 'charity', ['charity_id'], ['id'])
    op.add_column('volunteer', sa.Column('charity_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'volunteer', 'charity', ['charity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'volunteer', type_='foreignkey')
    op.drop_column('volunteer', 'charity_id')
    op.drop_constraint(None, 'contribution', type_='foreignkey')
    op.alter_column('contribution', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('contribution', 'charity_id')
    # ### end Alembic commands ###
